// ============================================================
// 箱子配置 — 替换照片/视频时只需修改这里
// layer: 1 = 第一层悬空（地面跳起可顶到）
//        2 = 第二层悬空（跳上台面，走到箱下再顶；箱子不接触台面）
//        3 = 第三层（台面在第二层上方 2.5 格，同样悬空 2.5 格）
//        4 = 第四层（同上规律继续叠高）
// onPipe: true = 放在管道口上（顶开后可能掉进管道）
//
// 共 20 个回忆：#1–#9 与 #12–#20 对应你按顺序命名的 18 张；
// #10 猫咪和小p（原 box4 照片）、#11 电🐔恶宝（原 box5 视频）位于中段。
// ============================================================
const BOX_CONFIG = [
  {
    id: 1,
    title: "大镜子自拍",
    caption: "对着大镜子自拍哦",
    type: "image",
    src: "assets/media/box1.jpg?v=2",
    coins: 6,
    layer: 1,
    onPipe: false,
  },
  {
    id: 2,
    title: "杭州嘎嘎能吃",
    caption: "在杭州嘎嘎能吃",
    type: "image",
    src: "assets/media/box2.jpg?v=2",
    coins: 7,
    layer: 2,
    onPipe: false,
  },
  {
    id: 3,
    title: "猫爬行李箱",
    caption: "有猫爬上行李箱了！",
    type: "video",
    src: "assets/media/box3.mp4?v=3",
    poster: "assets/media/box3_poster.jpg?v=3",
    coins: 8,
    layer: 1,
    onPipe: true,
  },
  {
    id: 4,
    title: "深圳湾",
    caption: "和糊糊去了深圳湾",
    type: "video",
    src: "assets/media/box4.mp4?v=3",
    poster: "assets/media/box4_poster.jpg?v=3",
    coins: 8,
    layer: 3,
    onPipe: false,
  },
  {
    id: 5,
    title: "中秋小灯笼",
    caption: "中秋小鸡笼小灯笼",
    captionHtml: "中秋小<del>鸡笼</del>小灯笼",
    type: "image",
    src: "assets/media/box5.jpg?v=2",
    coins: 6,
    layer: 1,
    onPipe: false,
  },
  {
    id: 6,
    title: "温柔眼神",
    caption: "温柔的眼神迸溅出浓浓的爱意",
    type: "image",
    src: "assets/media/box6.jpg?v=2",
    coins: 7,
    layer: 2,
    onPipe: false,
  },
  {
    id: 7,
    title: "长沙小龙虾",
    caption: "长沙小龙虾我们来啦！！",
    type: "video",
    src: "assets/media/box7.mp4?v=3",
    poster: "assets/media/box7_poster.jpg?v=3",
    coins: 9,
    layer: 4,
    onPipe: false,
  },
  {
    id: 8,
    title: "雪之T宝",
    caption: "雪之T宝",
    type: "video",
    src: "assets/media/box8.mp4?v=3",
    poster: "assets/media/box8_poster.jpg?v=3",
    coins: 6,
    layer: 1,
    onPipe: false,
  },
  {
    id: 9,
    title: "牛肉双蛋蒸米粉",
    caption: "带我宝去吃全深圳最好吃的牛肉双蛋蒸米粉",
    type: "video",
    src: "assets/media/box9.mp4?v=3",
    poster: "assets/media/box9_poster.jpg?v=3",
    coins: 8,
    layer: 2,
    onPipe: true,
  },
  {
    id: 10,
    title: "猫咪和小p",
    caption: "和小宝逛了家具展，然后去码头的咖啡店撸猫，拍到小猫的头和卡姿兰小宝",
    type: "image",
    src: "assets/media/box10.jpg?v=2",
    coins: 7,
    layer: 2,
    onPipe: false,
  },
  {
    id: 11,
    title: "电🐔恶宝",
    caption: "每次和小宝开电🐔都好开心呀！",
    type: "video",
    src: "assets/media/box11.mp4?v=3",
    poster: "assets/media/box11_poster.jpg?v=3",
    coins: 8,
    layer: 1,
    onPipe: false,
  },
  {
    id: 12,
    title: "偷瞄！",
    caption: "偷瞄！",
    type: "image",
    src: "assets/media/box12.jpg?v=2",
    coins: 8,
    layer: 3,
    onPipe: false,
  },
  {
    id: 13,
    title: "被偷瞄！",
    caption: "被偷瞄！",
    type: "image",
    src: "assets/media/box13.jpg?v=2",
    coins: 6,
    layer: 1,
    onPipe: false,
  },
  {
    id: 14,
    title: "云里镁铝",
    caption: "云里雾里，飞出一个镁铝",
    type: "video",
    src: "assets/media/box14.mp4?v=3",
    poster: "assets/media/box14_poster.jpg?v=3",
    coins: 7,
    layer: 2,
    onPipe: false,
  },
  {
    id: 15,
    title: "路灯与花花",
    caption: "路灯刚好洒在花花上呢",
    type: "image",
    src: "assets/media/box15.jpg?v=2",
    coins: 7,
    layer: 1,
    onPipe: true,
  },
  {
    id: 16,
    title: "咕噜咕噜",
    caption: "咕噜咕噜...",
    type: "image",
    src: "assets/media/box16.jpg?v=2",
    coins: 9,
    layer: 4,
    onPipe: false,
    extraLowStep: true,
  },
  {
    id: 17,
    title: "猫&猫",
    caption: "猫&猫",
    type: "image",
    src: "assets/media/box17.jpg?v=2",
    coins: 6,
    layer: 1,
    onPipe: false,
  },
  {
    id: 18,
    title: "后座猫",
    caption: "抓拍到后座猫",
    type: "image",
    src: "assets/media/box18.jpg?v=2",
    coins: 7,
    layer: 2,
    onPipe: false,
  },
  {
    id: 19,
    title: "这是哪里",
    caption: "大声告诉我我们这是在哪里！！！（我想不起来！）",
    type: "video",
    src: "assets/media/box19.mp4?v=3",
    poster: "assets/media/box19_poster.jpg?v=3",
    coins: 8,
    layer: 3,
    onPipe: false,
  },
  {
    id: 20,
    title: "同一块牌纸",
    caption: "和女大小宝举起同一块牌纸哦",
    type: "image",
    src: "assets/media/box20.jpg?v=2",
    coins: 7,
    layer: 1,
    onPipe: true,
  },
];

const MACHINE_JACKPOT_COINS = BOX_CONFIG.reduce((sum, b) => sum + b.coins, 0);
const MIN_COINS_TO_ENTER_MACHINE = Math.max(30, Math.floor(MACHINE_JACKPOT_COINS * 0.43));
